name: screentasia
description: A Flutter package that helps you create beautifully adaptive designs for all screens with a wealth of features.
version: 1.0.0
homepage: https://github.com/FaisalFaraj/screentasia
repository: https://github.com/FaisalFaraj/screentasia
screenshots:
  - description: screentasia logo.
    path: images/logo.jpg


# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
  
environment:
  sdk: ">=3.0.10 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
